Season 2023-2 January '24 Update
Re-Volt-America/RVA-Data pull request #10
Opened 2023-12-28 14:02 UTC by EstebanMz

- The following cars have been balanced:
**Rookie**
Toukka 4x4 (1.2 -> 1.1)

**Advanced**
Emperor (1.1 -> 1.0)

**Semi-Pro**
5TP (1.1 -> 0.9)
Otaku-D (1.0 -> 1.2)
Sidepod (1.1 -> 1.3)

**Pro**
Tegelhus (0.9 -> 1.2)
Truckenstein (0.9 -> 1.2)

- Fixed typos on Amateur and Advanced cars with 1.0 multiplier.

2023-12-31 23:57 UTC, EstebanMz commented
`models/cars/advanced.csv` looks like it was completely modified because I had a conflict recently, it should be fixed now.
The important changes dome in this commit are:
**Advanced:**
WILL (0.8 -> 0.9)
**Super Pro:**
Powerpython (0.7 -> 0.8)

2024-01-01 02:03 UTC, BGMP commented
I'll take a look when I'm back home @EstebanMz ! Thanks for handling this, and enjoy a happy new year!

2024-01-25 13:28 UTC, BGMP requested changes
Requires https://github.com/Re-Volt-America/rva_cars/pull/13

2024-01-25 19:25 UTC, BGMP approved these changes

2024-01-26 01:59 UTC, merged